csv_files:
  input: "image_descriptions.csv"
  enhanced_descriptions: "enhanced_descriptions.csv"
  images: "images.csv"

s3:
  bucket_name: "${S3_BUCKET_NAME}"
  input_key: "image_descriptions.csv"
  folder: "images"

stability_ai:
  steps: 30
  cfg_scale: 7.0
  width: 1024
  height: 1024
  samples: 1
  sampler: K_DPMPP_2M
  style_preset: "comic-book" # 3d-model analog-film anime cinematic comic-book digital-art enhance fantasy-art isometric line-art low-poly modeling-compound neon-punk origami photographic pixel-art tile-texture
  clip_guidance_preset: "FAST_BLUE"
  negative_prompt: "blurry, low quality, worst quality, low resolution, artifacts, oversaturated, text, watermark, logo, signature, out of frame, cropped, deformed, malformed, disfigured, bad anatomy, bad hands, duplicate"

output:
  directory: "generated_images"
  format: "png"