csv_files:
  input: "image_descriptions.csv"
  enhanced_descriptions: "enhanced_descriptions.csv"
  images: "images.csv"

s3:
  bucket_name: "${S3_BUCKET_NAME}"
  input_key: "image_descriptions.csv"
  
stability_ai:
  steps: 30
  cfg_scale: 7.0
  width: 1024
  height: 1024
  samples: 1
  sampler: K_DPMPP_2M
  style_preset: "photographic"
  clip_guidance_preset: "FAST_BLUE"

output:
  directory: "generated_images"
  format: "png"